### ISSUE TITLE
通过 npm 引入写法项目报错运行不起来

### ISSUE THREAD

**Issue by Curry3O** [JoeshuTT/version-polling#5]
在应用入口文件中代码如下：
```js
import { createVersionPolling } from 'version-polling'
import { Button, notification, Space } from 'antd'

createVersionPolling({
  appETagKey: '__APP_ETAG__',
  pollingInterval: 5 * 1000, // 单位为毫秒
  silent: process.env.NODE_ENV === 'development', // 开发环境下不检测
  onUpdate: (self) => {
    notification.info({
      message: '页面有新的功能更新，请您点击确定按钮刷新查看～',
      btn: (
        <Space>
          <Button
            size="small"
            onClick={() => {
              notification.destroy()
              self.onCancel()
            }}
          >
            取消
          </Button>
          <Button
            type="primary"
            size="small"
            onClick={() => {
              notification.destroy()
              self.onRefresh()
            }}
          >
            确认
          </Button>
        </Space>
      ),
    })
  },
})
```

页面报错内容：

```
Uncaught Error: Module parse failed: Unexpected token (278:35)
You may need an appropriate loader to handle this file type.
|             _this.stop();
| 
>             _this.options.onUpdate?.(_this);
|           }
|         };
    at ./node_modules/.pnpm/version-polling@1.2.5/node_modules/version-polling/dist/version-polling.js (value-equal.js:29:1)
    at __webpack_require__ (bootstrap:786:1)
    at fn (bootstrap:149:1)
    at Module.<anonymous> (index.css:45:1)
    at ./src/index.tsx (index.tsx:70:1)
    at __webpack_require__ (bootstrap:786:1)
    at fn (bootstrap:149:1)
    at 0 (utils.tsx:734:1)
    at __webpack_require__ (bootstrap:786:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCall
```

package.json 文件:
```bash
"react": "^17.0.1",
"webpack": "4.29.6",
"node": "v16.20.2",
```

**Comment by JoeshuTT** [comment]
nodeV14以上

**Comment by Curry3O** [comment]
> nodeV14以上

我的node版本是v16.20.2。
“通过 script 引入，直接插入到 HTML”这种写法是没问题的，就是上面这种写法会报错

**Comment by JoeshuTT** [comment]
## [我按照这个文档启动项目](https://ant.design/docs/react/use-with-create-react-app-cn)
## src/index.js
```
import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
import { createVersionPolling } from "version-polling/dist/version-polling.esm";
import { Button, notification, Space } from "antd";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
createVersionPolling({
  appETagKey: "__APP_ETAG__",
  pollingInterval: 5 * 1000, // 单位为毫秒
  // silent: process.env.NODE_ENV === "development", // 开发环境下不检测
  onUpdate: (self) => {
    notification.info({
      message: "页面有新的功能更新，请您点击确定按钮刷新查看～",
      btn: (
        <Space>
          <Button
            size="small"
            onClick={() => {
              notification.destroy();
              self.onCancel();
            }}
          >
            取消
          </Button>
          <Button
            type="primary"
            size="small"
            onClick={() => {
              notification.destroy();
              self.onRefresh();
            }}
          >
            确认
          </Button>
        </Space>
      ),
    });
  },
});

```
## 更新成功
![image](https://github.com/JoeshuTT/version-polling/assets/22463804/7d1351a7-dc84-4ff8-a692-f2b4fb9fc987)

**Comment by JoeshuTT** [comment]
qq 1442702103，有问题加这个qq备注version-polling

**Comment by Curry3O** [comment]
我这个react项目用了qiankun，如果只在基座写createVersionPolling代码，可以实时检测基座是否有新版本，但子应用代码发布新版后无法检测，改怎么做？也要到子应用代码里写createVersionPolling代码吗?
